name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker for GCR
      run: |
        echo "Configuring gcloud and Docker..."
        echo "$GCP_SA_KEY" > /tmp/key.json || true
        gcloud auth activate-service-account --key-file=/tmp/key.json
        gcloud auth configure-docker --quiet

    - name: Build and push container image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/accident-detection:${{ github.sha }}

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: accident-detection
        image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/accident-detection:${{ github.sha }}
        region: ${{ secrets.GCP_REGION }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        allow_unauthenticated: true
        env_vars: |
          PORT=8080
